// Auto-generated by https://github.com/react-spring/gltfjsx

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/scene.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="OSG_Scene">
        <group name="RootNode_(gltf_orientation_matrix)" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="RootNode_(model_correction_matrix)">
            <group name="skfb_offset" position={[-102253.52, -210688.86, -17050.52]}>
              <group>
                <mesh material={materials['Scene_-_Root']} geometry={nodes[''].geometry} />
                <mesh material={materials['Scene_-_Root']} geometry={nodes[''].geometry} />
                <mesh material={materials['Scene_-_Root']} geometry={nodes[''].geometry} />
                <mesh material={materials['Scene_-_Root']} geometry={nodes[''].geometry} />
              </group>
            </group>
          </group>
        </group>
      </scene>
    </group>
  )
}
